# Generated by Django 2.2.28 on 2023-09-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('contact', models.CharField(max_length=20, verbose_name='联系方式')),
                ('job_status', models.CharField(choices=[('积极找工作', '积极找工作'), ('暂不找工作', '暂不找工作')], max_length=20, verbose_name='求职状态')),
                ('job_expectation', models.TextField(verbose_name='求职期望')),
                ('work_experience', models.TextField(verbose_name='工作/实习经历')),
                ('project_experience', models.TextField(verbose_name='项目经历')),
                ('education', models.CharField(max_length=100, verbose_name='教育程度')),
                ('skills', models.TextField(verbose_name='专业技能')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='app1.JobSeeker')),
            ],
            options={
                'verbose_name': '个人简历',
                'verbose_name_plural': '个人简历',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companySize', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=20)),
                ('workName', models.CharField(max_length=100)),
                ('publishTime', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('workCity', models.CharField(max_length=50)),
                ('workingExp', models.CharField(max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.JobSeeker')),
            ],
        ),
    ]
