# Generated by Django 2.2.28 on 2023-09-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companySize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
