# Generated by Django 2.2.11 on 2023-09-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companySize', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=20)),
                ('workName', models.CharField(max_length=100)),
                ('publishTime', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('workCity', models.CharField(max_length=50)),
                ('workingExp', models.CharField(max_length=50)),
            ],
        ),
    ]
