# Generated by Django 2.2.11 on 2023-09-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
