# Generated by Django 2.2.28 on 2023-09-20 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230920_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publishTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
