# Generated by Django 2.2.28 on 2023-09-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230920_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='businessType',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
