# Generated by Django 2.2.28 on 2023-09-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_job_businesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='businessType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.Employer'),
        ),
    ]
