# Generated by Django 2.2.28 on 2023-09-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230920_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='publishTime',
        ),
    ]
