# Generated by Django 2.2.28 on 2023-09-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_status',
            field=models.CharField(choices=[('积极找工作', '积极找工作'), ('暂不找工作', '暂不找工作')], max_length=20, verbose_name='求职状态'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.JobSeeker')),
            ],
        ),
    ]
